DarkFlorist/lunaria

.prettierrc, app/index.html, build/vendor.ts, package-lock.json, package.json
Most modern browsers now support importmap except Safari. Open for discussion
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap
=> Removal of es-module-shims dependency

app/index.html, app/ts/components/App.tsx, app/ts/components/SendEthPage.tsx
When the page is first loaded, a flash of un-styled content happens while resources are being downloaded. This PR aims to reduce that "flicker" or "jankiness" feel to the app. This effect will be more pronounced once the app introduces handlers for page load and refresh such as #51 which this PR aims to prevent.
Miscellaneous addition:
- used "Lunaria" as brand
NOT included on this PR:
- splash screen icon design #52 
Temporary design
=> Prevent FOUC by adding splash screen

app/css/index.css, app/ts/components/App.tsx, app/ts/components/ConnectToWallet.tsx, app/ts/components/ErrorBoundary.tsx, app/ts/components/Layout.tsx, app/ts/components/SendEthPage.tsx, app/ts/components/TransactionDetailsPage.tsx, app/ts/components/TransactionPage.tsx, app/ts/components/TransferContext.tsx, app/ts/library/utilities.ts, app/ts/store/transfer.ts, twcss/tailwind.globals.css
WIP for Transaction details page
=> Inspect Transaction and Search Page

app/ts/library/utilities.ts
There's an issue when only Interceptor is installed and no MetaMask where window.ethereum is not recognized. Initial finding with regards the use of `chainId` property is not recommended and should be removed
=> Fix Interceptor window.ethereum not recognized

app/ts/components/Blockie.tsx
Blockie component accepts lower-case address
Resolves #96
=> Fix blockie generation

README.md, app/index.html
Resolves #130
Resolves #105 
Utilizing the svg on the main page should work, just need to review for other machines first.
| <img width="348" alt="Screenshot 2023-06-04 at 10 31 01 AM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/70aecff3-ee9b-4988-93b3-3896285b860a"> |
|:--:|
| *Using brave browser* |
Update:
- I just sneaked in the readme fix here as it's very small
=> Add Lunaria favicon

app/css/index.css, app/ts/components/TransferPage/Validation.tsx, app/ts/components/TransferPage/index.tsx, app/ts/store/transfer.ts
Resolves #108
| <img width="437" alt="Screenshot 2023-06-04 at 9 58 12 AM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/7d39cf99-2cfa-4ab8-8492-890b78b349ec"> | 
|:--:| 
| *If recipient address is the same as source* |
| <img width="437" alt="Screenshot 2023-06-04 at 9 57 57 AM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/6bc19f63-9aab-45b2-ba88-b16182eb76ae"> | 
|:--:| 
| *If recipient address is a token* |
=> Add validation for token address

app/ts/components/Favorites.tsx, app/ts/components/SVGBlockie.tsx, app/ts/components/TransactionPage/SaveTransfer.tsx, app/ts/components/TransferPage/Validation.tsx, app/ts/store/favorites.ts
Remove requirement for transfer label when saving a transaction
Resolves #145
=> Make save transfer label optional

app/ts/components/TokenManager/index.tsx, app/ts/store/tokens.ts
calling `contract.decimals()` now returns `bigint` type (previously number) so formatting with `formatUnits` throws and prevents the token from being saved.
alternatively, looked into converting all instances of decimals to bigint but until the `formatUnits` function natively supports it, would be less code to manage to cast it to Number for now
=> Fix add token functionality

build/package-lock.json, build/package.json, build/tsconfig.json, package-lock.json, tsconfig.json, typings/node/index.d.ts
A workaround from this template was applied to prevent issues from ethers.js' @node/types dependency when used on a browser environment
https://github.com/Zoltu/preact-es2015-template/blob/master/tsconfig.json#L28-L30
=> Remove @node/types and add workaround

app/ts/store/favorites.ts, app/ts/store/recent-transfers.ts
update coming from browser storage is causing cache to be corrupt. added checks that syncing from storage to state are mapped by it's corresponding keys
=> Add storage key check before update

app/ts/components/ConnectAccount.tsx, app/ts/components/TokenManager/EtherBalance.tsx, app/ts/components/TransactionPage/TransactionDetails.tsx, app/ts/library/ethereum.ts, app/ts/library/exceptions.ts, app/ts/store/account.ts, app/ts/store/network.ts, app/ts/store/provider.ts, app/ts/store/tokens.ts, app/ts/store/transaction.ts, app/ts/store/transfer.ts, app/ts/types.ts
Redeclared the useProvider response to be a getter. Some errors were silently swallowed (maybe within effects) which is hard to drill down to
=> Fix provider fail silently when using signal

app/css/index.css, app/ts/components/CopyButton.tsx, app/ts/components/TransferResult.tsx
Allow user view more details of an error and copy raw error message which can be handy for debugging
| <img width="989" alt="Screenshot 2023-11-07 at 9 12 53 AM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/b1704532-8414-4fe8-8e90-742b224d919a"> |
|:--:|
| *default view* |
| <img width="989" alt="Screenshot 2023-11-07 at 9 12 33 AM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/7344d686-3be9-45ee-a2d1-94ba873c0292"> |
|:--:|
| *expanded view* |
=> Enhance error message UI

app/ts/schema.ts
Ethers already does checksum so utilizing it to determine bad addresses
|variation|address|validation|
|--|--|--:|
| lowercase | `0x4b35d49dc14ee21b86bb0290b68f071b18a5fe96` | ✅ |
| uppercase | `0x4B35D49DC14EE21B86BB0290B68F071B18A5FE96` | ✅ |
| mixed-case (checksummed) | `0x4b35D49dC14EE21B86bb0290b68F071b18a5FE96` | ✅ |
| mixed-case (invalid checksum) | `0x4b35D49dC14EE21B86bb0290b68F071b18a5Fe96` | ❌ |
Fixes #222
=> Consider non-checksummed address as invalid address

app/ts/components/TokenPicker.tsx
Balance will now be only auto-updating when the token picker is open
Resolves #227
=> Only check token balance when necessary

tsconfig.vendor.json
Github Actions complains about `npm run vendor` having invalid tsconfig configuration
Resolves #239
=> Fix Workflow Build Issue

app/index.html, app/ts/components/Favorites.tsx, app/ts/components/TokenPicker.tsx, app/ts/components/TransactionPage/index.tsx, app/ts/components/TransferPage/index.tsx
- dynamically change the HTML base URL to the window's location
- changed absolute `/` paths to relative path `./`
Resolves #246
There may still be errors in the page before the base href was set but most modern browsers will find the files after the switch; at least on Chrome and Firefox was tested ok
=> Added support for hosting from a subfolder

.editorconfig
YAML is silly and requires spaces to work properly, so `.editorconfig` should say so.
=> Make yaml use spaces instead of tabs.

app/ts/components/SetupTransfer.tsx, app/ts/components/TransferPage/index.tsx
The selected template isn't applied when the page loads; clicking template correctly applies it tho
The token selection is correctly set with value coming from template, however, it is being set to ETH quickly afterwards
The selected token should be reset to ETH when the app detects a change in network (a contract address may only exist on the previous network). The reset function however is being triggered when the network's chain id is resolved (which happens when the page loads) instead of when it is being fetched again (when a chainChanged event happens)
_**The PR also included fix in anchor link for creating new/blank transfer_
---
Resolves #259
=> Fix template not loading on page load

.github/workflows/ipfs-deploy.yml
The hash line here is supposed to be a yaml comment but dealing with multi-line scripts, this syntax is invalid and will break the script.
https://github.com/DarkFlorist/lunaria/blob/94c546abb61cc7f090421705d4ee35e158290e61/.github/workflows/ipfs-deploy.yml#L122
=> Fix premature script exit
