DarkFlorist/lunaria

app/css/index.css
app/ts/components/App.tsx
app/ts/components/HashRouter.tsx

Build a url routing system based on location hash
<sup>[1]</sup> Exported a reusable function `useParams` to capture dynamic hash values `:dynamic_value`--word `\w+` preceeded by a semicolon

Hash Routing

---

.editorconfig
app/css/index.css
app/index.html
app/ts/components/App.tsx
app/ts/components/Blockie.tsx
app/ts/components/ConnectToWallet.tsx
app/ts/components/HashRouter.tsx
app/ts/components/Layout.tsx
app/ts/components/SendEthPage.tsx

This PR sets the stage for the send page layout, separating the functionality to next PR
- Send Page UI layout and grid work
- fix type issue from #43 `Vnode<RouteProps>`
Sample UI screens
<small>mobile (portrait)</small>
<small>HD / tablets / mobile (landscape)</small>
<small>Full HD / laptops</small> 
<small>wide displays</small>

Send Page UI Update

---

app/ts/components/App.tsx
app/ts/store/account.ts

This should satisfy the requirement on #40

Retain account session after page refresh

---

app/ts/components/AccountContext.tsx
app/ts/components/ConnectToWallet.tsx
app/ts/components/SendEthPage.tsx
app/ts/library/exceptions.ts
app/ts/store/account.ts

Addresses #64 which segregate address states
This also resolves #67 #65

Account store state rework

---

app/ts/components/ActiveNetwork.tsx
app/ts/components/Layout.tsx

Dynamic network UI as per raised here
https://github.com/DarkFlorist/web3-app/pull/72#pullrequestreview-1297045782

Add  Dynamic Network Component

---

app/ts/components/Balance.tsx
app/ts/components/Icon/Tokens/index.tsx
app/ts/components/TransferPage/ActiveAsset.tsx
app/ts/components/TransferPage/AssetListing.tsx
app/ts/components/TransferPage/FormFields.tsx

This addresses the issue where the form isn't available to play around without connecting to a wallet.
This PR also addresses comments from #79 and #81

Make transfer page available without connecting

---

LICENSE
README.md
package.json

Changes in brand from web3-app to Lunaria
Resolves #82

Changes in relation to brand name

---

app/css/index.css
app/ts/components/App.tsx
app/ts/components/Modal.tsx
app/ts/components/Notice.tsx
app/ts/store/notice.ts
app/ts/types.ts

Component will be used to catch errors and display to user

Add notify component for error handling

---

app/ts/components/TransferPage/ActiveAsset.tsx

Relates to #99
*Removed link to Issue as it may close it automatically*

Fix invalid icon path

---

app/css/index.css
app/ts/components/AssetsPage/index.tsx
app/ts/components/AsyncText.tsx
app/ts/components/ConnectAccount.tsx
app/ts/components/TransferPage/index.tsx
app/ts/store/account.ts
twcss/tailwind.globals.css

Separated the functions for the new UI into smaller PRs. This will have included

Re-implement connect component

---

app/ts/components/TokenManager/EtherBalance.tsx
app/ts/components/TokenManager/TokenBalance.tsx
app/ts/components/TokenManager/index.tsx

Added token balance to token cards
Resolves #117

Add balances to token card

---

app/ts/components/RecentTransfers.tsx
app/ts/components/TimeAgo.tsx
app/ts/store/recent-transfers.ts
app/ts/store/transfer.ts

| <img width="380" alt="Screenshot 2023-06-04 at 3 25 35 PM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/7718b4c5-9ef8-42ff-a3dc-b3e8242b3fe4"> |
|:--:|
| *Human readable time* |

More readable recent transfers

---

app/css/index.css
app/ts/components/MainFooter.tsx
app/ts/components/TransactionPage/index.tsx
app/ts/components/TransferPage/index.tsx

New footer design
Resolves #140

Footer Information

---

app/ts/components/TransferPage/Validation.tsx

This may need wordings, appreciate comments
Resolves #137

Add confirmation to transfer that has warnings

---

app/ts/components/RecentTransfers.tsx
app/ts/store/recent-transfers.ts
app/ts/store/transfer.ts

- add token name
- add token / eth value to label
Resolves #141

Recent Transfer Details Update

---

app/ts/components/AddressField.tsx
app/ts/components/Favorites.tsx
app/ts/components/SVGBlockie.tsx
app/ts/components/TransactionPage/SaveTransfer.tsx
app/ts/components/TransferPage/Validation.tsx
app/ts/components/TransferPage/index.tsx
app/ts/store/favorites.ts

Trim addresses on Address Field

---

app/ts/store/account.ts

Add address checksum

---

app/ts/components/TransactionPage/TransactionDetails.tsx
app/ts/library/ethereum.ts

Resolves #170 - fixed log parsing causing token save to not show up
Resolves #162 - added forward compatibility for ethers type issue https://github.com/ethers-io/ethers.js/issues/4029
Resolves #124 - ethers v6 update properly returns `null` if it fails to get transaction and is now properly handled

Updated log parsing function

---

package-lock.json
package.json

This should fix a reported issue with ETH transfer using TheInterceptor

Ethers.js upgrade v6.6.1 → v6.6.4

---

app/css/index.css
app/ts/components/ConnectAccount.tsx
app/ts/components/Modal.tsx
app/ts/store/network.ts
app/ts/store/notice.ts

Resolves #154 
Note: the css generation from tailwind changed a bit, this should not affect the current applied styles

Handle browser with no web3 wallet installed

---

app/css/index.css
app/ts/components/TokenManager/index.tsx

used the first two letters of the token name as default icon
etters of the token name

Dynamic default token icon

---

app/ts/components/QueryToken.tsx
app/ts/components/TransferPage/AddTokenDialog.tsx
app/ts/components/TransferPage/index.tsx
app/ts/library/constants.ts
app/ts/store/tokens.ts

Also in this PR:
- remove unused legacy token functions and checks

Automatically select custom token after adding

---

app/ts/components/TransactionPage/TransactionDetails.tsx
app/ts/components/TransactionPage/index.tsx

Remove balance after transaction

---

app/ts/library/human-ethers-errors.ts
package-lock.json
package.json

Fixes #169
Upgrades Ethers to 6.7.1
Adds human-readable-ethers-error.ts
@jubalm, you may want to style the error, I just display the plain text human error.

 Add human-ethers, add to transfer error

---

app/ts/components/AbbreviatedValue.tsx
app/ts/library/utilities.ts

Fix balance rendering issue

---

.github/workflows/ipfs-deploy.yml

The release output would be similar to this format
| <img width="584" alt="Screenshot 2024-02-24 at 11 17 48 PM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/d5abc05b-6a58-4959-ac10-bb020fc789f6"> |
| -- |
| *Sample Release* |

Add workflow step to publish a release

---

app/index.html
app/ts/components/App.tsx
app/ts/components/IPFSSubpathRedirect.tsx
build-scripts/vendor.mts
package-lock.json
package.json

UPDATED:
This should now automatically redirect when an IPFS subpath is detected instead of showing a warning

Redirect IPFS subpath using subdomain resolution

---

app/ts/components/AbbreviatedValue.tsx
app/ts/components/TokenPicker.tsx
app/ts/components/TransferHistory.tsx
app/ts/library/bigint.utils.ts

Sync this component with The Interceptor implementation

Updated abbreviate values component

---

app/css/index.css
app/ts/components/TokenAdd.tsx
tsconfig.json
twcss/package-lock.json
twcss/package.json
twcss/tailwind.globals.css

_* PR contains tailwind runner updates_

Token address checksum

---

app/css/index.css
app/ts/components/TokenAdd.tsx
app/ts/components/TransferAddressField.tsx
app/ts/components/TransferRecorder.tsx
app/ts/components/TransferResult.tsx
app/ts/schema.ts
tsconfig.json
twcss/package-lock.json
twcss/package.json
twcss/tailwind.globals.css

| <img width="523" alt="Screenshot 2024-06-07 at 3 03 00 PM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/8cdc6367-6802-43da-8636-bad512af85b8"> | <img width="573" alt="Screenshot 2024-06-27 at 3 49 35 PM" src="https://github.com/DarkFlorist/lunaria/assets/1169838/c34596b8-6bdc-4469-81a3-b34023f4c8a1"> |
|:--:|:--:|
|_transfer page_|_add token_|
Also included in this PR
- force line breaks on displaying lengthy error logs to prevent page from stretching

Add address checksum validation

---

Dockerfile

CI Build Fix

---

.github/workflows/deploy.yml
.github/workflows/ipfs-deploy.yml
Dockerfile
app/css/index.css
app/ts/components/MainFooter.tsx
app/ts/version.ts

Add version tag in footer to easily distinguish UI release

Add version id in footer

---

.github/workflows/deploy.yml

There was a mismatch of the variable used in the echo script and what's being declared

Fix version variable not correctly set

---

app/ts/components/TokenAdd.tsx
app/ts/components/TransferResult.tsx
app/ts/schema.ts

Allow erc20 token address in full or lower letter case
